insert into customer (firstname, lastname, email, mobile, job) values ('Rois', 'Daniele', 'rdaniele0@sakura.ne.jp', '5717196317', 'Senior Editor');
insert into customer (firstname, lastname, email, mobile, job) values ('Caddric', 'Bromwich', 'cbromwich1@yellowpages.com', '3271514192', 'Information Systems Manager');
insert into customer (firstname, lastname, email, mobile, job) values ('Cybill', 'Pyett', 'cpyett2@ocn.ne.jp', '4596611210', 'Software Engineer II');
insert into customer (firstname, lastname, email, mobile, job) values ('Prince', 'Scarce', 'pscarce3@1und1.de', '4414277245', 'Paralegal');
insert into customer (firstname, lastname, email, mobile, job) values ('Wilhelmine', 'Sparshott', 'wsparshott4@newsvine.com', '4742401984', 'Teacher');
insert into customer (firstname, lastname, email, mobile, job) values ('Ange', 'Scully', 'ascully5@vimeo.com', '7532319627', 'Assistant Media Planner');
insert into customer (firstname, lastname, email, mobile, job) values ('Kristoffer', 'Gaine', 'kgaine6@boston.com', '3393774923', 'Dental Hygienist');
insert into customer (firstname, lastname, email, mobile, job) values ('Astrid', 'Rospars', 'arospars7@aboutads.info', '1464185816', 'Graphic Designer');
insert into customer (firstname, lastname, email, mobile, job) values ('Nicky', 'Berrill', 'nberrill8@creativecommons.org', '3226228096', 'Senior Editor');
insert into customer (firstname, lastname, email, mobile, job) values ('Gisela', 'Russan', 'grussan9@reference.com', '8433318987', 'Financial Analyst');
insert into customer (firstname, lastname, email, mobile, job) values ('Justinian', 'Tolchard', 'jtolcharda@berkeley.edu', '6687920099', 'Mechanical Systems Engineer');
insert into customer (firstname, lastname, email, mobile, job) values ('Emilio', 'Wagon', 'ewagonb@jugem.jp', '9547588348', 'Payment Adjustment Coordinator');
insert into customer (firstname, lastname, email, mobile, job) values ('Garnet', 'Kintish', 'gkintishc@naver.com', '7533305295', 'Office Assistant I');
insert into customer (firstname, lastname, email, mobile, job) values ('Jaclyn', 'Oxbe', 'joxbed@sfgate.com', '1014409335', 'Design Engineer');
insert into customer (firstname, lastname, email, mobile, job) values ('Vere', 'Lawford', 'vlawforde@huffingtonpost.com', '1511578721', 'Senior Cost Accountant');
insert into customer (firstname, lastname, email, mobile, job) values ('Fern', 'Tomkinson', 'ftomkinsonf@clickbank.net', '9301964480', 'Help Desk Technician');
insert into customer (firstname, lastname, email, mobile, job) values ('Dewitt', 'Dwine', 'ddwineg@merriam-webster.com', '8996788738', 'Chief Design Engineer');
insert into customer (firstname, lastname, email, mobile, job) values ('Sofia', 'Funcheon', 'sfuncheonh@nature.com', '5036880693', 'Developer II');
insert into customer (firstname, lastname, email, mobile, job) values ('Olympie', 'Pahl', 'opahli@ox.ac.uk', '6008775159', 'Research Nurse');
insert into customer (firstname, lastname, email, mobile, job) values ('Stephine', 'Albany', 'salbanyj@hugedomains.com', '1832927711', 'Design Engineer');